import { StyleSheet } from "react-native";

export const ScoreboardStyles = StyleSheet.create({
  main: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 10,
    maxWidth: 1200,
    color: "white",
  },
  match: {
    color: "white",
    fontSize: 20,
    fontFamily: "System",
  },
  title: {
    fontSize: 25,
    fontFamily: "System",
    marginTop: 20,
    color: "#6AFF00",
    textTransform: "uppercase",
    alignSelf: "center",
    textAlign: "center",
    fontWeight: "bold",
  },
  score_container: {
    display: "flex",
  },
  score: {
    marginTop: 20,
    color: "#6AFF00",
    fontSize: 30,
    fontFamily: "System",
  },
  description_games_container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 40,
    width: "100%",
    // zIndex: 2,
    fontFamily: "System",
    position: "relative",
    padding: 10,
    backgroundColor: "rgba(0, 0, 0, 0.5)", // black with 50% opacity
    color: "#fff",
    borderWidth: 1,
    borderColor: "#282828",
    borderRadius: 8,
    margin: 15,
    alignSelf: "center",
  },
  section_title: {
    fontSize: 20,
    fontFamily: "System",
    marginTop: 20,
    color: "#A143F8",
  },
  button_container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 3,
    marginHorizontal: 20,
  },

  button_text: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    justifyContent: "center",
    alignItems: "center",
    letterSpacing: 0.25,
    fontFamily: "System",
  },

  button_start_game: {
    backgroundColor: "#05A7FF",
    padding: 20,
    borderRadius: 8,
    textAlign: "center",
    marginTop: 20,
    margin: "auto",
  },

  button_finish_game: {
    backgroundColor: "deeppink",
    padding: 20,
    borderRadius: 8,
    textAlign: "center",
    marginTop: 20,
  },
  button_change_score: {
    backgroundColor: "#585858",
    padding: 20,
    borderRadius: 8,
    textAlign: "center",
    marginTop: 20,
  },
  button_show_summary: {
    backgroundColor: "green",
    padding: 20,
    borderRadius: 8,
    textAlign: "center",
    marginTop: 20,
  },
  button_clear_scoreboard: {
    backgroundColor: "#0073FF",
    padding: 20,
    borderRadius: 8,
    textAlign: "center",
    marginTop: 20,
    maxWidth: 300,
  },
});
